### PR TITLE
Email signup

### PR DESCRIPTION
**Pull request by adborden**
I converted the html to markdown so it's a bit easier to work with. The mailchimp email submission form was a bit jumbled up, so I sorted that out, too. I also added a few notes about how to run the site locally before pushing to github pages.

Preview: https://future-of-california.sites.adborden.net/

### CODE REVIEW

**Comment by christophertull** [comment]
Epic!

**Comment by adborden** [comment]
The README is a separate file than what's get built into the website (index.md). I probably lost a little formatting and links when I converted it to markdown. GitHub pages takes the repo and then builds the website using [Jekyll](https://jekyllrb.com/), with a few restrictions. By default, README.* is ignored by Jekyll. If you want to update the links, you'll want to update `index.md`.

Instead of keeping the content in two places, you might just want to have the README.md link to the index.md file on GitHub.

**Comment by christophertull** [comment]
Is there a way to point jekyll at `README.md` instead of `index.md`? If so that would be an option but then we would have the signup form HTML cluttering the bottom of the README.

**Comment by adborden** [comment]
On Fri, 2018-12-14 at 12:50 -0800, Christopher Tull <notifications@github.com> wrote:
> Is there a way to point jekyll at `README.md` instead of `index.md`?
> If so that would be an option but then we would have the signup form
> HTML cluttering the bottom of the README.

There's no great way to do this. I would keep the readme focused on how
to contribute, and direct people to the website for the principles.

--
Aaron D Borden
Human and Hacker

**Comment by patwater** [comment]
Roger rogue leader. Please see #16 for a PR to fix the links and made the readme a bit more of a well readme (lol) rather than the actual main public tech text. Looked good locally (after a n00b battle with ruby install stuff) though appreciate a quick glance before merging in to make sure I'm not screwing anything up. 1t1d

**Pull request merged**
